[workspace]
members = [
    "todo-list-common",
    "todo-list-backend",
    "todo-list-frontend", "todo-list-cli",
]

# Optional: this ensures all crates share the same dependency versions
resolver = "2"
